name: Merge Queue
on:
  pull_request:
    types: [labeled, unlabeled, synchronize]

jobs:
  prioritize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set priority
        run: |
          if [[ "${{ github.event.label.name }}" == "high-priority" ]]; then
            echo "PR is high-priority"
            # Trigger merge action or re-order queue
          elif [[ "${{ github.event.label.name }}" == "medium-priority" ]]; then
            echo "PR is medium-priority"
          else
            echo "PR is low-priority"
          fi
